site_name: Jony4
site_url: https://jony4.pro
repo_url: https://github.com/jony4/jony4
repo_name: jony4/jony4
copyright: Copyright &copy; 2021 -  Jony4
theme:
  name: material
  palette:
    primary: teal
    accent: light blue
  font: true
  language: zh
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.tabs
    # - navigation.expand
    # - navigation.indexes
    - navigation.instant
  icon:
    repo: fontawesome/brands/git-alt  
extra:
  homepage: https://jony4.pro
  disqus: jony4
  analytics:
    provider: google
    property: G-XVWRQ8MT20
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rigongyizu
    - icon: fontawesome/brands/github
      link: https://github.com/jony4
    - icon: fontawesome/solid/paper-plane
      link: mailto:<im@jony4.pro>

markdown_extensions:
  - pymdownx.tasklist:
      clickable_checkbox: true
extra_javascript:
  # - https://unpkg.com/gitalk/dist/gitalk.min.js
  # - https://raw.githubusercontent.com/jony4/blog/master/javascripts/extra.js
extra_css:
  # - https://unpkg.com/gitalk/dist/gitalk.css
