site_name: Jony4
site_url: https://jony4.pro
repo_name: jony4/jony4
copyright: Copyright &copy; 2021 - Now Jony4
theme:
  name: material
  palette:
    primary: indigo
    accent: light blue
  font: true
  language: zh
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
  icon:
    repo: fontawesome/brands/git-alt  
extra:
  homepage: https://jony4.pro
  analytics:
    provider: google
    property: G-XVWRQ8MT20
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jony4pro
    - icon: fontawesome/brands/github
      link: https://github.com/jony4
    - icon: fontawesome/solid/paper-plane
      link: mailto:<im@jony4.pro>

markdown_extensions:
  - pymdownx.tasklist:
      clickable_checkbox: true
